### ISSUE TITLE
report id prompt wont work on ios

### ISSUE THREAD

**Issue by rafaelcorsi** [insper-education/active-handout#16]
No meu celular o prompt para pedir o dado do usuário não aparece quando abro no safari-ios.

https://github.com/insper-education/active-handout/blob/265b52d7feccae386c11c1db22504ccab87f1aa2/content/js/report.js#L37

Uma ideia é trocar o prompt por alguma outra coisa.. um form modal?

https://jqueryui.com/dialog/#modal-form

**Comment by toshikurauchi** [comment]
Pelo que entendi, vocês não querem que mostre a página se não estiver autenticado, certo? Não poderia redirecionar para uma tela de login?

**Comment by rafaelcorsi** [comment]
@toshikurauchi  a questão é que não aparece o promp para eu poder inserir meu user

**Comment by toshikurauchi** [comment]
@rafaelcorsi mas se redirecionasse pra outra página nem precisaria de prompt, não é?

**Comment by igordsm** [comment]
Not relevant anymore
