### ISSUE TITLE
Avisar aluno que página está desatualizada

### ISSUE THREAD

**Issue by rafaelcorsi** [insper-education/active-handout#21]
Acontece muitas vezes do aluno estar com a página aberta no navegador com uma versão antiga, poderíamos indicar para o aluno atualizar a página.

**Comment by igordsm** [comment]
Minha sugestão seria fazer usando setInterval, fazer um fetch `HEAD` e olhar para o cabeçalho Last-Modified.

**Comment by cicerotcv** [comment]
O deploy da página ocorre só quando o código do Github muda ou tem como atualizar o conteúdo do site localmente? Dependendo de como for, dá pra usar o `setInterval` que o @igordsm sugeriu com e fazer uma requisição periodicamente na API do GitHub.

Fazendo um **GET** em `https://api.github.com/repos/insper-education/active-handout` a gente obtém o momento do último push

```javascript
{ 
// ...
  "created_at": "2021-03-30T17:08:42Z",
  "updated_at": "2021-05-19T22:26:50Z",
  "pushed_at": "2021-05-13T18:33:10Z",
// ...
}
```

**Comment by rafaelcorsi** [comment]
@cicerotcv não precisamos fazer um request na api do github, só precisamos dar um novo get própria página:

➜  ~ curl -I https://insper-education.github.io/active-handout/
```
HTTP/2 200 
server: GitHub.com
....
last-modified: Thu, 13 May 2021 18:33:19 GMT
...
```

Eu sugiro usar a informação do github.io ao do arquivo no github pq usamos o actions do  para dar o deploy na página e isso leva alguns minutos para acontecer, então vai ter um momento que o arquivo markdown está atualizado e o site não e se o aluno der refresh vai continuar desatualizado.

Alguma ideia de como seria a notificação? Banner?

**Comment by toshikurauchi** [comment]
Que tal um snackbar: https://www.w3schools.com/howto/howto_js_snackbar.asp

Mas eu deixaria ele com um X pra fechar ao invés de fechar depois de um
tempo. Ou até já com um botão pra atualizar a página. Melhor ainda seria se
ele atualizasse de forma assíncrona e só mostrasse a notificação falando
que a página foi atualizada. Poderia até, temporariamente, dar um highlight
de outra cor no texto que tiver mudado, mas aí acho que já estou viajando.

**Comment by rafaelcorsi** [comment]
@toshikurauchi uhm... que tal criarmos um plugin para notificações? Ai qualquer módulo que precisar usar notificação faz por ele...

**Comment by toshikurauchi** [comment]
Gosto dessa ideia!
