### ISSUE TITLE
Remover admonition dos detalhes de uma pergunta (quiz, short-question)

### ISSUE THREAD

**Issue by rafaelcorsi** [insper-education/active-handout#25]
Acho que fica muito poluído um box dentro de outro, sugiro apenas remover o admonition da resposta, talvez mudar alguma na fonte para marcar que o texto pertence a resposta e não pergunta.

![image](https://user-images.githubusercontent.com/1039615/119246945-35dd1a00-bb5c-11eb-9aa6-484126e0f195.png)

![image](https://user-images.githubusercontent.com/1039615/119246960-52795200-bb5c-11eb-8ca6-3c1e2e12cff3.png)

**Comment by igordsm** [comment]
Bom, para o quiz isso seria fácil: tudo depois das opções poderia ser a resposta. Já para a pergunta escrita já fica mais delicado. 

Concordo que box aninhado fica meio feio. Alguma sugestão de como poderíamos organizar isso diferente? Quem sabe com a resposta **fora** do box fique melhor?

**Comment by rafaelcorsi** [comment]
A minha ideia é manter o admonition detais na criação do quiz e só tirar ele na hora de exibir.
