### ISSUE TITLE
Erro slides.pdf quando a página não tem slides

### ISSUE THREAD

**Issue by rafaelcorsi** [insper-education/active-handout#27]
Exemplo: https://insper-education.github.io/active-handout/reference/basic-editing/
 
![2021-05-23-122727_1864x709_scrot](https://user-images.githubusercontent.com/1039615/119266748-635cae80-bbc2-11eb-843a-663132fe2784.png)

**Comment by igordsm** [comment]
Isso não é um erro. Eu lanço o request e checo o código de erro. Se for 404 ele trata e não muda a página. É assim que é identificado se slides.pdf existe. Eu fecharia.

**Comment by rafaelcorsi** [comment]
não rola mascarar isso? com algo do tipo`xhr.addEventListener('error', );` ou pegando o `status == 400`  (não testei)
