### ISSUE TITLE
Usar camel case

### ISSUE THREAD

**Issue by toshikurauchi** [insper-education/active-handout#28]
O código está usando `snake_case`, mas em JS o padrão é [`lowerCamelCase`](https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Code_guidelines/JavaScript#variable_naming). 

Devemos atualizar os nomes de variáveis e funções para camel case.

**Comment by williamars** [comment]
Essa issue parece bem tranquila. Como eu não entendi muito ainda algumas coisas do código, vou fazê-la, assim eu consigo fazer uma feature e já ir compreendendo melhor o JS.
