### ISSUE TITLE
"Last edited by {user} in {date}"

### ISSUE THREAD

**Issue by igordsm** [insper-education/active-handout#4]
Add date of last modification in footer.

**Comment by rafaelcorsi** [comment]
Parece que o material já tem essa feature:

https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#revision-date-localized

![image](https://user-images.githubusercontent.com/1039615/114061125-73b40680-986c-11eb-8647-857fb8792a1e.png)

**Comment by rafaelcorsi** [comment]
Na verdade ele só coloca a data: 

![image](https://user-images.githubusercontent.com/1039615/114061970-5f243e00-986d-11eb-874b-125be068357c.png)

Podemos melhorar isso com uma extensão nossa usando como base o código em 

https://github.com/timvink/mkdocs-git-revision-date-localized-plugin
