### ISSUE TITLE
Progress button

### ISSUE THREAD

**Issue by rafaelcorsi** [insper-education/active-handout#9]
Dois tipo:

- [ ] Revela o resto da página
- [ ] Só reporta o progresso

Dúvidas:

- [ ] Usar botão do material? https://squidfunk.github.io/mkdocs-material/reference/buttons/
- [ ] Botão que reinicia os Checkpoints?
- [x] O botão some e não tem mais nenhuma ref. para o aluno que ali era um checkpoint, podemos colocar uma linha no lugar?

**Comment by rafaelcorsi** [comment]
talking to some students they said they don't like the feeling of not knowing the total size of the handout, because the progress button hides the page

**Comment by LuisHFB** [comment]
We can add a progress bar to show progress, other way is to track progress by vertical scrolling
